### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by hvze** [nerd/PropertySystem#1]
Parser.java.... Parsers.java?
Please name your classes correctly, if anything you could combine the two.

**Comment by nerd** [comment]
I don't see the problem with this. There's naming like this within Java itself. Do have suggestions of what you would like to change it to? If not, I'm closing this.

**Comment by hvze** [comment]
I go by, if you are forced to named things like these, you need to rewrite it. There should never be a situation where this is acceptable. (This isn't enterprise code, plus the fact that its open source makes it even more an issue about naming... You don't want those who use it to get confused do you?)

**Comment by nerd** [comment]
Tell the developers of Java to rename Executors then. Since you don't have any real suggestions, this is getting closed.
